### ISSUE TITLE
Rapid sliding on refresh of page

### ISSUE THREAD

**Issue by DaveBeirne** [CodyHouse/cd-animated-cards-changelog#1]
Hi,

I integrated and test the Animated Cards component and it works beautifully on Safari, Opera, MS Edge, Chrome on loading the page. But when you refresh the same page the slide speeds up to a very rapid speed and i cant figure out why.

Example:
Url: https://www.greenstock.no/web/
_( View at the bottom for Our Partners )_ 

![rapid-Sliding](https://user-images.githubusercontent.com/1081103/81935746-0b6f8d00-95e9-11ea-87bb-1c0d2ec8404c.gif)

**Comment by claudia-romano** [comment]
Hi Dave,
we just pushed an updated version of this component with some JS improvements. You can get the updated JS code here:
https://codyhouse.co/ds/components/app/animated-cards

Unfortunately I was not able to reproduce the bug you are experiencing on my local version. Is that specific to a browser?

If you are still experiencing it after the update of the code, would that be possible for you to recreate the bug on a demo which is not part of a complex website? So that I can check it on my side as well. Thanks.

**Comment by DaveBeirne** [comment]
That update worked Claudia, Thank you!!

It was happening on all browsers before so it was strange... but not any more :)
